### ISSUE TITLE
Trying to contact you

### ISSUE THREAD

**Issue by Corey-Code** [piratelinux/Pirate-Linux#4]
Andrew, I know this is not the most professional way to contact you.

**Comment by Corey-Code** [comment]
Putting this in comment so it can be deleted later if needed. I have had no luck tracking you down in the Bitmark discord and would rather not post directly on the bitcointalk forum. Please get ahold of me on discord. https://discord.gg/QhV2Wx6

**Comment by piratelinux** [comment]
Hi my username on discord is akrmn
